### ISSUE TITLE
Kiji exports the `node_type` symbol

### ISSUE THREAD

**Issue by tenderlove** [twitter-forks/rubyenterpriseedition187-248#1]
Kiji exports a `node_type` symbol.  This symbol conflicts with libxml2.  Because of that, [nokogiri cannot be compiled on kiji](https://github.com/tenderlove/nokogiri/issues/448).

**Comment by bitbckt** [comment]
This was not fixed by https://github.com/twitter/rubyenterpriseedition187-248/commit/34bee2099834731315e569d45b511232c9c3e40b ...?

**Comment by bitbckt** [comment]
Whoops... hit comment/close.

**Comment by szegedi** [comment]
Hi,

this is supposed to have fixed it in Kiji 0.11:
https://github.com/twitter/rubyenterpriseedition187-248/commit/34bee2099834731315e569d45b511232c9c3e40b

Do you still have the problem with latest Kiji source code?

Attila.

**Comment by tmm1** [comment]
I can confirm nokogiri 1.4.4 compiles and runs fine with kiji 0.11
