### ISSUE TITLE
Kiji appears to deep freeze arrays and hashes

### ISSUE THREAD

**Issue by ghost** [twitter-forks/rubyenterpriseedition187-248#3]
We've been using Kiji over at PipelineDeals.com and have run into a recurring issue where Kiji deep freezes arrays, which we believe is incorrect (as 1.8.7 and 1.9.2 do not). In the following example, one of our developers freezes an array containing a single string.  The array should be frozen.  The items contained in the array should not.

Aeolus:/Users/kwerle/Source/vpim% rvm use system
Now using system ruby.
Aeolus:/Users/kwerle/Source/vpim% ruby -e 'puts ["foo"].freeze[0].frozen?'
false
Aeolus:/Users/kwerle/Source/vpim% rvm use 1.9.2
Using /Users/kwerle/.rvm/gems/ruby-1.9.2-p180
Aeolus:/Users/kwerle/Source/vpim% ruby -e 'puts ["foo"].freeze[0].frozen?'
false
Aeolus:/Users/kwerle/Source/vpim% rvm use kiji
Using /Users/kwerle/.rvm/gems/kiji-head
Aeolus:/Users/kwerle/Source/vpim% ruby -e 'puts ["foo"].freeze[0].frozen?'
true

And the same thing with hashes, of course.

Aeolus:/Users/kwerle/Source/vpim% rvm use system
Now using system ruby.
Aeolus:/Users/kwerle/Source/vpim% ruby -e 'puts({"foo" => "bar"}.freeze["foo"].frozen?)'
false
Aeolus:/Users/kwerle/Source/vpim% rvm use kiji
Using /Users/kwerle/.rvm/gems/kiji-head
Aeolus:/Users/kwerle/Source/vpim% ruby -e 'puts({"foo" => "bar"}.freeze["foo"].frozen?)'
true

Any thoughts? Intentional or bug?

**Comment by kwerle** [comment]
This is affecting us because we use third party gems which do things like (example trivialized)
array_of_strings.freeze
array_of_strings.each{|s| s.downcase!}
and expect this to work.

**Comment by evan** [comment]
This is an intentional change, and does technically break Ruby. Freeze moves objects into the longlife heap, so deep freezing strings results in some pretty big boosts in performance for static configuration and stuff.

Ideally the library author would not rely on the bizarre idiom of freeze-and-modify, even for dependent objects.
